import React from "react";
import { Container, Typography, Box, Paper, Divider } from "@mui/material";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";

const TermsOfService: React.FC = () => {
  return (
    <>
      <Navbar />

      {/* Hero Section */}
      <Box
        sx={{
          width: "100%",
          py: 8,
          textAlign: "center",
          background: "linear-gradient(135deg,#2563EB 0%,#1E40AF 100%)",
          borderBottom: "1px solid #ddd"
        }}
      >
        <Typography variant="h3" fontWeight="700">
          Terms of Service
        </Typography>
        <Typography variant="subtitle1" color="text.secondary" mt={1}>
          Please read our terms carefully before using our AI skin analysis service.
        </Typography>
      </Box>

      <Container maxWidth="md" sx={{ py: 6 }}>
        <Paper elevation={3} sx={{ p: 4, borderRadius: 3 }}>
          
          {/* Section */}
          <Typography variant="h5" fontWeight="600" gutterBottom>
            1. Introduction
          </Typography>
          <Typography paragraph sx={{ lineHeight: 1.8 }}>
            By accessing and using this website, you agree to the following Terms
            of Service. If you do not agree, please discontinue use immediately.
          </Typography>
          <Divider sx={{ my: 3 }} />

          <Typography variant="h5" fontWeight="600" gutterBottom>
            2. Purpose of the Service
          </Typography>
          <Typography paragraph sx={{ lineHeight: 1.8 }}>
            This website provides an AI-based skin lesion analysis tool using a
            Convolutional Neural Network (CNN) trained on the HAM10000 dataset.
            The results are informational only and not a substitute for medical
            diagnosis.
          </Typography>
          <Divider sx={{ my: 3 }} />

          <Typography variant="h5" fontWeight="600" gutterBottom>
            3. No Medical Advice
          </Typography>
          <Typography paragraph sx={{ lineHeight: 1.8 }}>
            The AI predictions generated by this tool do not constitute medical
            advice. Always consult a qualified healthcare professional for
            medical concerns or diagnosis.
          </Typography>
          <Divider sx={{ my: 3 }} />

          <Typography variant="h5" fontWeight="600" gutterBottom>
            4. Model Limitations
          </Typography>
          <Typography paragraph sx={{ lineHeight: 1.8 }}>
            The model is limited by the HAM10000 dataset and may produce
            inaccurate or biased results. Use the tool at your own discretion.
          </Typography>
          <Divider sx={{ my: 3 }} />

          <Typography variant="h5" fontWeight="600" gutterBottom>
            5. User Responsibilities
          </Typography>
          <Typography paragraph sx={{ lineHeight: 1.8 }}>
            Users must upload only images they have permission to use and must
            not upload harmful or malicious files.
          </Typography>
          <Divider sx={{ my: 3 }} />

          <Typography variant="h5" fontWeight="600" gutterBottom>
            6. Privacy & Data Handling
          </Typography>
          <Typography paragraph sx={{ lineHeight: 1.8 }}>
            Uploaded images are processed temporarily and not stored permanently.
            No data is shared externally without consent.
          </Typography>
          <Divider sx={{ my: 3 }} />

          <Typography variant="h5" fontWeight="600" gutterBottom>
            7. Limitation of Liability
          </Typography>
          <Typography paragraph sx={{ lineHeight: 1.8 }}>
            The website owner is not responsible for any actions taken based on
            the AI model’s output.
          </Typography>

        </Paper>
      </Container>

      <Footer />
    </>
  );
};

export default TermsOfService;
